#ifndef MEXT2_FS_EXT2_H
#define MEXT2_FS_EXT2_H

#include <stdint.h>

#define EXT2_SUPERBLOCK_PARTITION_BLOCK_OFFSET 2

/**** REVISION NUMBERS ****/
#define EXT2_GOOD_OLD_REV 0
#define EXT2_DYNAMIC_REV 1

/**** EXT2_GOOD_OLD_REV SPECIFIC ****/
#define EXT2_GOOD_OLD_INODE_SIZE 128
#define EXT2_GOOD_OLD_FIRST_INO 11

#define EXT2_NO_FEATURES 0
/**** EXT2 COMPATIBLE FEATURES  ****/
#define EXT2_FEATURE_COMPAT_DIR_PREALLOC    0x0001
#define EXT2_FEATURE_COMPAT_IMAGIC_INODES   0x0002
#define EXT3_FEATURE_COMPAT_HAS_JOURNAL     0x0004
#define EXT2_FEATURE_COMPAT_EXT_ATTR        0x0008
#define EXT2_FEATURE_COMPAT_RESIZE_INO      0x0010
#define EXT2_FEATURE_COMPAT_DIR_INDEX       0x0020

#define MEXT2_FEATURES_COMPAT (EXT2_NO_FEATURES)

/**** EXT2 INCOMPATIBLE FEATURES  ****/
#define EXT2_FEATURE_INCOMPAT_COMPRESSION   0x0001
#define EXT2_FEATURE_INCOMPAT_FILETYPE      0x0002
#define EXT3_FEATURE_INCOMPAT_RECOVER       0x0004
#define EXT3_FEATURE_INCOMPAT_JOURNAL_DEV   0x0008
#define EXT2_FEATURE_INCOMPAT_META_BG       0x0010

#define MEXT2_FEATURES_INCOMPAT (EXT2_FEATURE_INCOMPAT_FILETYPE)

/**** EXT2 COMPATIBLE READ-ONLY FEATURES ****/
#define EXT2_FEATURE_RO_COMPAT_SPARSE_SUPER 0x0001
#define EXT2_FEATURE_RO_COMPAT_LARGE_FILE   0x0002
#define EXT2_FEATURE_RO_COMPAT_BTREE_DIR    0x0004

#define MEXT2_FEATURES_RO_COMPAT (EXT2_FEATURE_RO_COMPAT_SPARSE_SUPER | EXT2_FEATURE_RO_COMPAT_LARGE_FILE)


struct mext2_ext2_superblock;
struct mext2_sd;

uint8_t mext2_ext2_sd_parser(struct mext2_sd* sd, struct mext2_ext2_superblock* superblock);
uint32_t inode_no_lookup(struct mext2_sd*, char* path);

#endif
