#ifndef MEXT2_COMMON_LIMITS_H
#define MEXT2_COMMON_LIMITS_H

#define MEXT2_MAX_FILE_NUMBER 16

#define MEXT2_USEFULL_BLOCKS_SIZE 8
/* MINIMAL VALUE SHOULD BE AT LEAST 2
 * IN ORDER TO CONTAIN SUPERBLOCK AND MBR */

#define MEXT2_MAX_FILENAME_LENGTH 32

#define MEXT2_MAX_BLOCK_NO_LIST_SIZE 8

#endif
