#ifndef MEXT2_COMMON_LIMITS_H
#define MEXT2_COMMON_LIMITS_H

#define MEXT2_MAX_FILE_NUMBER 16

#define MEXT2_USEFULL_BLOCKS_SIZE 2 // MINIMAL VALUE SHOULD BE AT LEAST 2 IN ORDER TO CONTAIN SUPERBLOCK AND MBR

#endif
